# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e93f9be3295f9f029c83addff422c822b25da2a0c13e2d3389d76e4b5f1be45812d4b8fe3d306fc1b23e7b38ba6ce02bdf60b3a9a98ca9ce660b7c111e95917e

test:
  secret_key_base: 36df717594ef0ee835a7a978ff060bd18f674fb5cdc56d3eb37143d27ee5c9b9ddf73ab02c3a1c66ecbb43cd3cb3be9a8dd65b0b3176107665b94648c9b77ed1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
